apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickhouse-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: clickhouse
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signoz-query-service-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: signoz-query-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signoz-frontend-pdb
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: signoz-frontend
