apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: cert-manager
spec:
  provider:
    gcpsm:
      projectId: docker-1210
      auth:
        workloadIdentity:
          clusterLocation: europe-west2
          clusterName: backstage-prod
          serviceAccountRef:
            name: cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-dns-sa
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: cert-manager-dns-sa
    creationPolicy: Owner
  data:
  - secretKey: key.json
    remoteRef:
      key: cert-manager-dns-sa-key
