apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - backstage.kofiray.net
    secretName: backstage-tls
  rules:
  - host: backstage.kofiray.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backstage
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
    ingress.cilium.io/service-type: "ClusterIP"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - argocd.kofiray.net
    secretName: argocd-tls
  rules:
  - host: argocd.kofiray.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
