apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-store
spec:
  provider:
    gcpsm:
      projectId: docker-1210
      auth:
        workloadIdentity:
          clusterLocation: europe-west2
          clusterName: backstage-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
