apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
    ingress.cilium.io/force-https: "disabled"
    external-dns.alpha.kubernetes.io/hostname: backstage.kofiray.net
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - backstage.kofiray.net
    secretName: backstage-tls
  rules:
  - host: backstage.kofiray.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backstage
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "argocd-ingress-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    external-dns.alpha.kubernetes.io/hostname: argocd.kofiray.net
spec:
  tls:
  - hosts:
    - argocd.kofiray.net
    secretName: argocd-tls
  rules:
  - host: argocd.kofiray.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
