apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "backstage-ingress-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.gcp.kubernetes.io/pre-shared-cert: "backstage-tls"
spec:
  tls:
  - host: backstage.kofiray.net # Will be replaced by Terraform
    secretName: backstage-tls
  rules:
  - host: backstage.kofiray.net # Will be replaced by Terraform
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backstage
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "backstage-ingress-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/whitelist-source-range: "86.177.222.87/32"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
  - hosts:
    - argocd.kofiray.net # Will be replaced by Terraform
    secretName: argocd-tls
  rules:
  - host: argocd.kofiray.net # Will be replaced by Terraform
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
